---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pig-upms-biz
  name: pig-upms-biz
  namespace: pig-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: pig-upms-biz
  template:
    metadata:
      labels:
        app: pig-upms-biz
    spec:
      containers:
        - image: registry.cn-shenzhen.aliyuncs.com/c-hh/pig-upms-biz:$BUILD_NUMBER
          imagePullPolicy: Always
          name: pig-upms-biz
          ports:
            - containerPort: 4000
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          readinessProbe:
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            tcpSocket:
              port: 4000
          livenessProbe:
            initialDelaySeconds: 100
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            tcpSocket:
              port: 4000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pig-upms-biz
  name: pig-upms-biz
  namespace: pig-dev
spec:
  ports:
    - name: http
      port: 4000
      protocol: TCP
      targetPort: 4000
      nodePort: 31204
  selector:
    app: pig-upms-biz
  sessionAffinity: None
  type: NodePort
