---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pig-gateway
  name: pig-gateway
  namespace: pig-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: pig-gateway
  template:
    metadata:
      labels:
        app: pig-gateway
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - image: registry.cn-shenzhen.aliyuncs.com/c-hh/pig-gateway:1.0.0
          imagePullPolicy: Always
          name: pig-gateway
          ports:
            - containerPort: 9999
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          readinessProbe:
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            tcpSocket:
              port: 9999
          livenessProbe:
            initialDelaySeconds: 100
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            tcpSocket:
              port: 9999
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pig-gateway
  name: pig-gateway
  namespace: pig-dev
spec:
  ports:
    - name: http
      port: 9999
      protocol: TCP
      targetPort: 9999
      nodePort: 31201
  selector:
    app: pig-gateway
  sessionAffinity: None
  type: NodePort
