apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pig-front
  namespace: pig-dev
spec:
  rules:
    - host: pig.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pig-front
              port:
                number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pig-front
  name: pig-front
  namespace: pig-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: pig-front
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pig-front
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - image: registry.cn-shenzhen.aliyuncs.com/c-hh/pig-front:1.0.0
          imagePullPolicy: Always
          name: pig-front
          ports:
            - containerPort: 80
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              port: 80
              path: /
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              port: 80
              path: /
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pig-front
  name: pig-front
  namespace: pig-dev
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31200
  selector:
    app: pig-front
  sessionAffinity: None
  type: NodePort
