apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pig-monitor
  name: pig-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pig-monitor
  template:
    metadata:
      labels:
        app: pig-monitor
    spec:
      containers:
      - image: pig-monitor:1.0.0
        name: pig-monitor
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pig-monitor
  name: pig-monitor
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: pig-monitor
  type: ClusterIP

